{settings_paths: {destrete_depths_path: /core/etc/destrete_depths.yaml, example_data_path: /tests/etc/data/,
    export_path: /exports/, mapping_parameter_path: /core/etc/mapping_parameter.yaml, seabird_smhi_path: /core/etc/seabird_smhi.yaml,
    template_path: /templates/Format Physical and chemical.xlsx, template_parameters_path: /core/etc/template_parameters.yaml, 
    archive_structure_path: /templates/archive_structure}}
